//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperZapatos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid ARTICLE_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> TOTAL_IN_SHELF { get; set; }
        public Nullable<decimal> TOTAL_IN_VAULT { get; set; }
        public Nullable<System.Guid> STORE_ID { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
